exports.queries = {
    login: () => {
        return `
        SELECT
            GEFUNCIONARIOS.CODUSUARIO,
            GEUSUARIO.NOME,
            GEUSUARIO.EMAIL,
            GEUSUARIO.TOKEN
        FROM HINOERP_BIO.GEFUNCIONARIOS GEFUNCIONARIOS
        LEFT JOIN 
            (SELECT 
                CODUSUARIO,
                NOME,
                EMAIL,
                SENHA TOKEN
            FROM HINOERP_BIO.GEUSUARIOS) GEUSUARIO
            ON GEFUNCIONARIOS.CODUSUARIO = GEUSUARIO.CODUSUARIO

        WHERE
            GEUSUARIO.CODUSUARIO = '${usuario}' 
            AND SENHAMOBILE = '${senha}'
        `;
    },
    lastStartNote: `
    SELECT
        CODINIAPT
    FROM 
        HINOERP_BIO.PDAPTINICIOPROD
    ORDER BY 
        DTINICIO DESC
    FETCH FIRST ROW ONLY
    `,
    lastEndNote: `
    SELECT
        CODFIMAPT
    FROM 
        HINOERP_BIO.PDAPTTERMINOPROD
    ORDER BY 
        DTTERMINO DESC
    FETCH FIRST ROW ONLY
    `,
    lastNote: `
    SELECT
        CODLANCAMENTO
    FROM HINOERP_BIO.PDLANCAMENTOS
    ORDER BY 
        CODLANCAMENTO DESC
    FETCH FIRST 1 ROW ONLY
    `,
    listRoutines: `
    SELECT 
        CODROTINA, DESCRICAO
    FROM HINOERP_BIO.ENROTINAS 
    ORDER BY DESCRICAO
    `,
    getNotes: (weekTarget) => {
        return `
        SELECT 
            GERAIS.*, ROTINA.CODROTINA, INFOCOLABORADOR.NOME, MAQUINASINFO.DESCRICAOMAQ,
            
            CASE WHEN STATUSCRITICIDADE = 'CRÍTICO'
            THEN 4
            ELSE 
                CASE WHEN DTINICIO IS NOT NULL AND DTTERMINO IS NULL
                THEN 2
                ELSE
                    CASE WHEN QUANTIDADE = 0
                    THEN 3
                    ELSE
                        CASE WHEN SEMANAANO = '${weekTarget}'
                        THEN 1
                        ELSE 0 END
                    
                    END
                END
            
            END AS STATUS
            
        FROM(
            SELECT 
                OPSPROGRAMADAS.CODTIPO, OPSPROGRAMADAS.CODORDPROD, INFOPRODUTO.CODPRODUTO, INFOPRODUTO.DESCRICAO, OPSPROGRAMADAS.DATAPROGRAMADA, SEMANAANO, STATUSCRITICIDADE,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO
                THEN LASTAPTMOBILE.NIVELORDPROD 
                ELSE LASTLANCAMENTO.NO_NIVELORDPROD 
                END AS NIVELORDPROD,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.OPERACAO 
                ELSE LASTLANCAMENTO.NO_OPERACAO 
                END AS OPERACAO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.DTINICIO 
                ELSE LASTLANCAMENTO.DTINICIO END AS DTINICIO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.DTTERMINO    
                ELSE LASTLANCAMENTO.DTTERMINO END AS DTTERMINO,
                
                LASTLANCAMENTO.QUANTIDADE,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODFUNCIONARIO 
                ELSE LASTLANCAMENTO.CODFUNCIONARIO END AS CODFUNCIONARIO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODMAQUINA 
                ELSE LASTLANCAMENTO.CODMAQUINA END AS CODMAQUINA,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODESTRUTURA 
                ELSE LASTLANCAMENTO.NO_CODESTRUTURA 
                END AS CODESTRUTURA,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTLANCAMENTO.DTTERMINO 
                ELSE DISPONIBILIDADE.DISPONIVELDESDE END AS DISPONIVELDESDE
                
            FROM (
                SELECT 
                    A.CODORDPROD, A.DTTERMINO DATAPROGRAMADA, B.CODTIPO, 
                    TO_NUMBER(TO_CHAR(TO_DATE(A.DTTERMINO,'DD/MM/YYYY'),'WW')) || '.' || TO_NUMBER(TO_CHAR(TO_DATE(A.DTTERMINO,'DD/MM/YYYY'),'YY')) AS SEMANAANO,
                    C.STATUSCRITICIDADE
                FROM HINOERP_BIO.PDORDEMPROD A
                LEFT JOIN(
                    SELECT 
                        B.CODPRODUTO, B.CODTIPO
                    FROM HINOERP_BIO.FSPRODUTOPARAMESTAB B ) B
                    ON B.CODPRODUTO = A.CODPRODUTO
                LEFT JOIN(
                    SELECT 
                        CODORDPROD, MATERIALCRITICO STATUSCRITICIDADE
                    FROM HINOERP_BIO.PEORDEMPROD
                    WHERE NIVELORDPROD = '1.1') C
                    ON C.CODORDPROD = A.CODORDPROD
                WHERE 
                    A.STATUS = 'P' AND A.NIVELORDPROD = '1.1' ) OPSPROGRAMADAS
                    
            LEFT JOIN (
                SELECT
                    FILTER.CODORDPROD, INFORMATION.NIVELORDPROD, INFORMATION.OPERACAO, INFORMATION.DTINICIO, INFORMATION.DTTERMINO, INFORMATION.QUANTIDADE, INFORMATION.CODFUNCIONARIO, INFORMATION.CODMAQUINA, INFORMATION.CODESTRUTURA, 
                    PROXIMAOPERACAO.NO_OPERACAO, PROXIMAOPERACAO.NO_CODORDPROD, PROXIMAOPERACAO.NO_NIVELORDPROD, PROXIMAOPERACAO.NO_CODESTRUTURA
                FROM(
                    SELECT 
                        CODORDPROD, 
                        MAX(CODLANCAMENTO) CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS
                    GROUP BY CODORDPROD) FILTER
                LEFT JOIN(
                    SELECT 
                        CODORDPROD, NIVELORDPROD, OPERACAO, DTINICIO, DTTERMINO, QUANTIDADE, CODFUNCIONARIO, CODMAQUINA, CODESTRUTURA, CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS) INFORMATION
                    ON INFORMATION.CODLANCAMENTO = FILTER.CODLANCAMENTO
                
                LEFT JOIN(
                    SELECT
                        FILTER.CODORDPROD NO_CODORDPROD, FILTER.ROWNUMBER, INFORMATION.OPERACAO NO_OPERACAO, INFORMATION.NIVELORDPROD NO_NIVELORDPROD, INFORMATION.CODESTRUTURA NO_CODESTRUTURA
                    FROM (
                        SELECT
                            CODORDPROD, MAX(ROWNUMBER) AS ROWNUMBER
                        FROM(
                            SELECT
                                ROW_NUMBER() OVER (ORDER BY CODORDPROD, NIVELORDPROD, OPERACAO DESC)AS ROWNUMBER,CODORDPROD, OPERACAO, NIVELORDPROD, CODESTRUTURA
                            FROM HINOERP_BIO.PDORDEMPRODROTINAS
                            WHERE QTDEPRODUCAO = 0)
                        GROUP BY CODORDPROD) FILTER
                        
                    LEFT JOIN(
                        SELECT
                            ROW_NUMBER() OVER (ORDER BY CODORDPROD, NIVELORDPROD, OPERACAO DESC)AS ROWNUMBER,CODORDPROD, OPERACAO, NIVELORDPROD, CODESTRUTURA
                        FROM HINOERP_BIO.PDORDEMPRODROTINAS
                        WHERE QTDEPRODUCAO = 0)INFORMATION
                        ON INFORMATION.CODORDPROD = FILTER.CODORDPROD AND INFORMATION.ROWNUMBER = FILTER.ROWNUMBER) PROXIMAOPERACAO
                    ON FILTER.CODORDPROD = PROXIMAOPERACAO.NO_CODORDPROD
                
                ) LASTLANCAMENTO
                ON LASTLANCAMENTO.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
                
            LEFT JOIN(
                SELECT 
                FILTER.CODORDPROD,
                INFORMATIONSTARTNOTE.NIVELORDPROD, INFORMATIONSTARTNOTE.OPERACAO, 
                INFORMATIONSTARTNOTE.DTINICIO, INFORMATIONENDNOTE.DTTERMINO, 
                INFORMATIONENDNOTE.QUANTIDADE, INFORMATIONSTARTNOTE.CODFUNCIONARIO, 
                INFORMATIONSTARTNOTE.CODMAQUINA, INFORMATIONSTARTNOTE.CODESTRUTURA
                FROM (SELECT 
                    CODORDPROD, MAX(CODINIAPT) CODINIAPT
                FROM HINOERP_BIO.PDAPTINICIOPROD
                GROUP BY CODORDPROD) FILTER
                
                LEFT JOIN(
                    SELECT 
                        NIVELORDPROD, OPERACAO, DTINICIO, CODINIAPT, CODFUNCIONARIO, CODMAQUINA, CODESTRUTURA
                    FROM HINOERP_BIO.PDAPTINICIOPROD
                    ORDER BY CODINIAPT DESC) INFORMATIONSTARTNOTE
                    ON INFORMATIONSTARTNOTE.CODINIAPT = FILTER.CODINIAPT
                    
                LEFT JOIN (
                    SELECT 
                        DTTERMINO, QUANTIDADE, CODINIAPT
                    FROM HINOERP_BIO.PDAPTTERMINOPROD) INFORMATIONENDNOTE
                ON INFORMATIONENDNOTE.CODINIAPT = INFORMATIONSTARTNOTE.CODINIAPT) LASTAPTMOBILE
                ON LASTAPTMOBILE.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
            LEFT JOIN(
                SELECT
                    FILTRO.CODORDPROD,
                    FILTRO.CODLANCAMENTO,
                    INFO.DTTERMINO DISPONIVELDESDE
                FROM(
                    SELECT CODORDPROD, MAX(CODLANCAMENTO) AS CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS
                    GROUP BY CODORDPROD
                    ORDER BY CODORDPROD) FILTRO
                LEFT JOIN(
                    SELECT 
                        DTTERMINO, CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS) INFO
                    ON INFO.CODLANCAMENTO = FILTRO.CODLANCAMENTO) DISPONIBILIDADE
                    ON OPSPROGRAMADAS.CODORDPROD = DISPONIBILIDADE.CODORDPROD
            LEFT JOIN(
                SELECT
                    CODIGO.CODORDPROD, CODIGO.CODPRODUTO, DESCRICOES.DESCRICAO
                FROM HINOERP_BIO.PDORDEMPROD CODIGO
                LEFT JOIN HINOERP_BIO.FSPRODUTO DESCRICOES
                ON DESCRICOES.CODPRODUTO = CODIGO.CODPRODUTO
                WHERE NIVELORDPROD = '1.1') INFOPRODUTO
                ON INFOPRODUTO.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
            
            ORDER BY OPSPROGRAMADAS.DATAPROGRAMADA, OPSPROGRAMADAS.CODTIPO, OPSPROGRAMADAS.CODORDPROD) GERAIS
        LEFT JOIN(
            SELECT
                CODESTRUTURA, OPERACAO, CODROTINA, CODORDPROD, NIVELORDPROD
            FROM HINOERP_BIO.PDORDEMPRODROTINAS) ROTINA
            ON GERAIS.CODESTRUTURA = ROTINA.CODESTRUTURA AND GERAIS.OPERACAO = ROTINA.OPERACAO AND GERAIS.NIVELORDPROD = ROTINA.NIVELORDPROD AND GERAIS.CODORDPROD = ROTINA.CODORDPROD
        LEFT JOIN(
            SELECT 
                *
            FROM (
                SELECT 
                    FUNCIONARIOUSER.CODFUNCIONARIO, NOMES.NOME
                FROM HINOERP_BIO.GEUSUARIOS NOMES
                JOIN (
                    SELECT 
                        CODFUNCIONARIO, CODUSUARIO
                    FROM HINOERP_BIO.GEFUNCIONARIOS) FUNCIONARIOUSER
                ON FUNCIONARIOUSER.CODUSUARIO = NOMES.CODUSUARIO)) INFOCOLABORADOR
                ON INFOCOLABORADOR.CODFUNCIONARIO = GERAIS.CODFUNCIONARIO
        LEFT JOIN (
            SELECT 
                DESCRICAO DESCRICAOMAQ, CODMAQUINA
            FROM HINOERP_BIO.ENMAQUINAS) MAQUINASINFO
            ON MAQUINASINFO.CODMAQUINA = GERAIS.CODMAQUINA
        ORDER BY CODROTINA, STATUS DESC, GERAIS.CODORDPROD
        `;
    },
    login: (usuario, senha) => {
        return `
          SELECT
              GEFUNCIONARIOS.CODUSUARIO,
              GEUSUARIO.NOME,
              GEUSUARIO.EMAIL,
              GEUSUARIO.TOKEN
          FROM HINOERP_BIO.GEFUNCIONARIOS GEFUNCIONARIOS
          LEFT JOIN 
              (SELECT 
                  CODUSUARIO,
                  NOME,
                  EMAIL,
                  SENHA TOKEN
              FROM HINOERP_BIO.GEUSUARIOS) GEUSUARIO
              ON GEFUNCIONARIOS.CODUSUARIO = GEUSUARIO.CODUSUARIO
      
          WHERE
              GEUSUARIO.CODUSUARIO = '${usuario}' 
              AND SENHAMOBILE = '${senha}'
          `;
    },
    validateToken: (token) => {
        return `
          SELECT
              GEFUNCIONARIOS.CODUSUARIO,
              GEUSUARIO.NOME,
              GEUSUARIO.EMAIL
          FROM HINOERP_BIO.GEFUNCIONARIOS GEFUNCIONARIOS
          LEFT JOIN 
              (SELECT 
                  CODUSUARIO,
                  NOME,
                  EMAIL,
                  SENHA TOKEN
              FROM HINOERP_BIO.GEUSUARIOS) GEUSUARIO
              ON GEFUNCIONARIOS.CODUSUARIO = GEUSUARIO.CODUSUARIO
      
          WHERE
              GEUSUARIO.TOKEN = '${token}'
          `;
    },
    getPredictedRealizated: (weekTarget) => {
        return `
        SELECT
            CODROTINA,
            PREVISTO,
            REALIZADO,
            ROUND((REALIZADO / PREVISTO) *100,2) AS PERCENTUAL,
            CODTIPO

        FROM (
            SELECT 
                ROTINAS.CODROTINA, 
                SUM(INFORMATION.PREVISTO) PREVISTO,
                SUM(CASE WHEN ROTINAS.QTDEPRODUCAO + INFORMATION.REFUGADO = INFORMATION.PREVISTO OR ROTINAS.QTDEPRODUCAO = 0 THEN ROTINAS.QTDEPRODUCAO 
                ELSE INFORMATION.PREVISTO END) AS REALIZADO,
                INFORMATION.CODTIPO
            
            FROM HINOERP_BIO.PDORDEMPRODROTINAS ROTINAS
            
            LEFT JOIN(
                SELECT 
                    GERAIS.CODORDPROD, MAX(GERAIS.PROGRAMADO) AS PREVISTO, MAX(GERAIS.REFUGADO) AS REFUGADO, FSTIPO.CODTIPO, MAX(DTTERMINO) 
                FROM HINOERP_BIO.PDORDEMPROD GERAIS
                LEFT JOIN(
                    SELECT 
                        CODPRODUTO, CODTIPO
                    FROM HINOERP_BIO.FSPRODUTOPARAMESTAB) FSTIPO
                    ON GERAIS.CODPRODUTO = FSTIPO.CODPRODUTO
                    
                    WHERE GERAIS.STATUS = 'P' AND GERAIS.NIVELORDPROD = '1.1' AND 
                    TO_NUMBER(TO_CHAR(TO_DATE(GERAIS.DTTERMINO,'DD/MM/YYYY'),'WW')) || '.' || TO_NUMBER(TO_CHAR(TO_DATE(GERAIS.DTTERMINO,'DD/MM/YYYY'),'YY')) = '${weekTarget}'
                    
                    GROUP BY GERAIS.CODORDPROD, FSTIPO.CODTIPO) INFORMATION
                ON INFORMATION.CODORDPROD = ROTINAS.CODORDPROD
                
                WHERE INFORMATION.CODTIPO IN(700,300)
                
                GROUP BY ROTINAS.CODROTINA, INFORMATION.CODTIPO
                ORDER BY INFORMATION.CODTIPO, ROTINAS.CODROTINA)
        `;
    },
    listSummaryWeeks: `
    SELECT 
        INFO.SEMANA || '.' || INFO.ANO SEMANA, MIN(INFO.DATAPROGRAMADA)MINDATA, MAX(INFO.DATAPROGRAMADA) MAXDATA, SUM(INFO.PROGRAMADO) QUANTIDADE
    FROM HINOERP_BIO.FSPRODUTO FILTER
    RIGHT JOIN (
        SELECT 
            PDORDEMPROD.CODPRODUTO, PDORDEMPROD.PROGRAMADO, PDORDEMPROD.DTTERMINO DATAPROGRAMADA, 
            TO_NUMBER(TO_CHAR(TO_DATE(PDORDEMPROD.DTTERMINO,'DD/MM/YYYY'),'WW')) AS SEMANA, 
            TO_NUMBER(TO_CHAR(TO_DATE(PDORDEMPROD.DTTERMINO,'DD/MM/YYYY'),'YY')) AS ANO
        FROM HINOERP_BIO.PDORDEMPROD PDORDEMPROD
        
        LEFT JOIN(
            SELECT 
                CODPRODUTO, CODTIPO
            FROM HINOERP_BIO.FSPRODUTOPARAMESTAB) PARAMCODTIPO
            ON PARAMCODTIPO.CODPRODUTO = PDORDEMPROD.CODPRODUTO

        WHERE PDORDEMPROD.NIVELORDPROD = '1.1' AND PARAMCODTIPO.CODTIPO = 700) INFO
        ON FILTER.CODPRODUTO = INFO.CODPRODUTO

    GROUP BY 
        INFO.SEMANA, INFO.ANO

    ORDER BY 
        INFO.ANO DESC, INFO.SEMANA DESC
    `,
    getListOrdersWeekSelected: (weekYear) => `
    SELECT 
        INFO.CODORDPROD, INFO.CODPRODUTO, FILTER.DESCRICAO, INFO.PROGRAMADO, INFO.DATAPROGRAMADA, INFO.SEMANAANO
    FROM HINOERP_BIO.FSPRODUTO FILTER
    RIGHT JOIN (
        SELECT 
            PDORDEMPROD.CODORDPROD, PDORDEMPROD.CODPRODUTO, PDORDEMPROD.PROGRAMADO, PDORDEMPROD.DTTERMINO DATAPROGRAMADA, 
            TO_NUMBER(TO_CHAR(TO_DATE(PDORDEMPROD.DTTERMINO,'DD/MM/YYYY'),'WW')) ||'.'|| TO_NUMBER(TO_CHAR(TO_DATE(PDORDEMPROD.DTTERMINO,'DD/MM/YYYY'),'YY')) AS SEMANAANO
        FROM HINOERP_BIO.PDORDEMPROD PDORDEMPROD
        
        LEFT JOIN(
            SELECT CODPRODUTO, CODTIPO
            FROM HINOERP_BIO.FSPRODUTOPARAMESTAB) FSCODTIPO
            
            ON FSCODTIPO.CODPRODUTO = PDORDEMPROD.CODPRODUTO
        
            WHERE PDORDEMPROD.NIVELORDPROD = '1.1' AND FSCODTIPO.CODTIPO = 700) INFO
        ON FILTER.CODPRODUTO = INFO.CODPRODUTO

    WHERE INFO.SEMANAANO = ${weekYear}

    ORDER BY INFO.CODPRODUTO, INFO.CODORDPROD
    `,
    getNotesMobile: (weekTarget, routines) => {
        return `
        SELECT 
            GERAIS.*, ROTINA.CODROTINA, INFOCOLABORADOR.NOME, MAQUINASINFO.DESCRICAOMAQ,
            
            CASE WHEN STATUSCRITICIDADE = 'CRÍTICO'
            THEN 4
            ELSE 
                CASE WHEN DTINICIO IS NOT NULL AND DTTERMINO IS NULL
                THEN 2
                ELSE
                    CASE WHEN QUANTIDADE = 0
                    THEN 3
                    ELSE
                        CASE WHEN SEMANAANO = '${weekTarget}'
                        THEN 1
                        ELSE 0 END
                    
                    END
                END
            
            END AS STATUS
            
        FROM(
            SELECT 
                OPSPROGRAMADAS.CODTIPO, OPSPROGRAMADAS.CODORDPROD, INFOPRODUTO.CODPRODUTO, INFOPRODUTO.DESCRICAO, OPSPROGRAMADAS.DATAPROGRAMADA, SEMANAANO, STATUSCRITICIDADE,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO
                THEN LASTAPTMOBILE.NIVELORDPROD 
                ELSE LASTLANCAMENTO.NO_NIVELORDPROD 
                END AS NIVELORDPROD,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.OPERACAO 
                ELSE LASTLANCAMENTO.NO_OPERACAO 
                END AS OPERACAO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.DTINICIO 
                ELSE LASTLANCAMENTO.DTINICIO END AS DTINICIO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.DTTERMINO    
                ELSE LASTLANCAMENTO.DTTERMINO END AS DTTERMINO,
                
                LASTLANCAMENTO.QUANTIDADE,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODFUNCIONARIO 
                ELSE LASTLANCAMENTO.CODFUNCIONARIO END AS CODFUNCIONARIO,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODMAQUINA 
                ELSE LASTLANCAMENTO.CODMAQUINA END AS CODMAQUINA,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTAPTMOBILE.CODESTRUTURA 
                ELSE LASTLANCAMENTO.NO_CODESTRUTURA 
                END AS CODESTRUTURA,
                
                CASE WHEN LASTLANCAMENTO.NIVELORDPROD != LASTAPTMOBILE.NIVELORDPROD OR LASTLANCAMENTO.OPERACAO != LASTAPTMOBILE.OPERACAO OR (LASTAPTMOBILE.DTTERMINO IS NULL AND LASTLANCAMENTO.NIVELORDPROD = LASTAPTMOBILE.NIVELORDPROD AND LASTLANCAMENTO.OPERACAO = LASTAPTMOBILE.OPERACAO)
                THEN LASTLANCAMENTO.DTTERMINO 
                ELSE DISPONIBILIDADE.DISPONIVELDESDE END AS DISPONIVELDESDE
                
            FROM (
                SELECT 
                    A.CODORDPROD, A.DTTERMINO DATAPROGRAMADA, B.CODTIPO, 
                    TO_NUMBER(TO_CHAR(TO_DATE(A.DTTERMINO,'DD/MM/YYYY'),'WW')) || '.' || TO_NUMBER(TO_CHAR(TO_DATE(A.DTTERMINO,'DD/MM/YYYY'),'YY')) AS SEMANAANO,
                    C.STATUSCRITICIDADE
                FROM HINOERP_BIO.PDORDEMPROD A
                LEFT JOIN(
                    SELECT 
                        B.CODPRODUTO, B.CODTIPO
                    FROM HINOERP_BIO.FSPRODUTOPARAMESTAB B ) B
                    ON B.CODPRODUTO = A.CODPRODUTO
                LEFT JOIN(
                    SELECT 
                        CODORDPROD, MATERIALCRITICO STATUSCRITICIDADE
                    FROM HINOERP_BIO.PEORDEMPROD
                    WHERE NIVELORDPROD = '1.1') C
                    ON C.CODORDPROD = A.CODORDPROD
                WHERE 
                    A.STATUS = 'P' AND A.NIVELORDPROD = '1.1' ) OPSPROGRAMADAS
                    
            LEFT JOIN (
                SELECT
                    FILTER.CODORDPROD, INFORMATION.NIVELORDPROD, INFORMATION.OPERACAO, INFORMATION.DTINICIO, INFORMATION.DTTERMINO, INFORMATION.QUANTIDADE, INFORMATION.CODFUNCIONARIO, INFORMATION.CODMAQUINA, INFORMATION.CODESTRUTURA, 
                    PROXIMAOPERACAO.NO_OPERACAO, PROXIMAOPERACAO.NO_CODORDPROD, PROXIMAOPERACAO.NO_NIVELORDPROD, PROXIMAOPERACAO.NO_CODESTRUTURA
                FROM(
                    SELECT 
                        CODORDPROD, 
                        MAX(CODLANCAMENTO) CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS
                    GROUP BY CODORDPROD) FILTER
                LEFT JOIN(
                    SELECT 
                        CODORDPROD, NIVELORDPROD, OPERACAO, DTINICIO, DTTERMINO, QUANTIDADE, CODFUNCIONARIO, CODMAQUINA, CODESTRUTURA, CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS) INFORMATION
                    ON INFORMATION.CODLANCAMENTO = FILTER.CODLANCAMENTO
                
                LEFT JOIN(
                    SELECT
                        FILTER.CODORDPROD NO_CODORDPROD, FILTER.ROWNUMBER, INFORMATION.OPERACAO NO_OPERACAO, INFORMATION.NIVELORDPROD NO_NIVELORDPROD, INFORMATION.CODESTRUTURA NO_CODESTRUTURA
                    FROM (
                        SELECT
                            CODORDPROD, MAX(ROWNUMBER) AS ROWNUMBER
                        FROM(
                            SELECT
                                ROW_NUMBER() OVER (ORDER BY CODORDPROD, NIVELORDPROD, OPERACAO DESC)AS ROWNUMBER,CODORDPROD, OPERACAO, NIVELORDPROD, CODESTRUTURA
                            FROM HINOERP_BIO.PDORDEMPRODROTINAS
                            WHERE QTDEPRODUCAO = 0)
                        GROUP BY CODORDPROD) FILTER
                        
                    LEFT JOIN(
                        SELECT
                            ROW_NUMBER() OVER (ORDER BY CODORDPROD, NIVELORDPROD, OPERACAO DESC)AS ROWNUMBER,CODORDPROD, OPERACAO, NIVELORDPROD, CODESTRUTURA
                        FROM HINOERP_BIO.PDORDEMPRODROTINAS
                        WHERE QTDEPRODUCAO = 0)INFORMATION
                        ON INFORMATION.CODORDPROD = FILTER.CODORDPROD AND INFORMATION.ROWNUMBER = FILTER.ROWNUMBER) PROXIMAOPERACAO
                    ON FILTER.CODORDPROD = PROXIMAOPERACAO.NO_CODORDPROD
                
                ) LASTLANCAMENTO
                ON LASTLANCAMENTO.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
                
            LEFT JOIN(
                SELECT 
                FILTER.CODORDPROD,
                INFORMATIONSTARTNOTE.NIVELORDPROD, INFORMATIONSTARTNOTE.OPERACAO, 
                INFORMATIONSTARTNOTE.DTINICIO, INFORMATIONENDNOTE.DTTERMINO, 
                INFORMATIONENDNOTE.QUANTIDADE, INFORMATIONSTARTNOTE.CODFUNCIONARIO, 
                INFORMATIONSTARTNOTE.CODMAQUINA, INFORMATIONSTARTNOTE.CODESTRUTURA
                FROM (SELECT 
                    CODORDPROD, MAX(CODINIAPT) CODINIAPT
                FROM HINOERP_BIO.PDAPTINICIOPROD
                GROUP BY CODORDPROD) FILTER
                
                LEFT JOIN(
                    SELECT 
                        NIVELORDPROD, OPERACAO, DTINICIO, CODINIAPT, CODFUNCIONARIO, CODMAQUINA, CODESTRUTURA
                    FROM HINOERP_BIO.PDAPTINICIOPROD
                    ORDER BY CODINIAPT DESC) INFORMATIONSTARTNOTE
                    ON INFORMATIONSTARTNOTE.CODINIAPT = FILTER.CODINIAPT
                    
                LEFT JOIN (
                    SELECT 
                        DTTERMINO, QUANTIDADE, CODINIAPT
                    FROM HINOERP_BIO.PDAPTTERMINOPROD) INFORMATIONENDNOTE
                ON INFORMATIONENDNOTE.CODINIAPT = INFORMATIONSTARTNOTE.CODINIAPT) LASTAPTMOBILE
                ON LASTAPTMOBILE.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
            LEFT JOIN(
                SELECT
                    FILTRO.CODORDPROD,
                    FILTRO.CODLANCAMENTO,
                    INFO.DTTERMINO DISPONIVELDESDE
                FROM(
                    SELECT CODORDPROD, MAX(CODLANCAMENTO) AS CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS
                    GROUP BY CODORDPROD
                    ORDER BY CODORDPROD) FILTRO
                LEFT JOIN(
                    SELECT 
                        DTTERMINO, CODLANCAMENTO
                    FROM HINOERP_BIO.PDLANCAMENTOS) INFO
                    ON INFO.CODLANCAMENTO = FILTRO.CODLANCAMENTO) DISPONIBILIDADE
                    ON OPSPROGRAMADAS.CODORDPROD = DISPONIBILIDADE.CODORDPROD
            LEFT JOIN(
                SELECT
                    CODIGO.CODORDPROD, CODIGO.CODPRODUTO, DESCRICOES.DESCRICAO
                FROM HINOERP_BIO.PDORDEMPROD CODIGO
                LEFT JOIN HINOERP_BIO.FSPRODUTO DESCRICOES
                ON DESCRICOES.CODPRODUTO = CODIGO.CODPRODUTO
                WHERE NIVELORDPROD = '1.1') INFOPRODUTO
                ON INFOPRODUTO.CODORDPROD = OPSPROGRAMADAS.CODORDPROD
            
            ORDER BY OPSPROGRAMADAS.DATAPROGRAMADA, OPSPROGRAMADAS.CODTIPO, OPSPROGRAMADAS.CODORDPROD) GERAIS
        LEFT JOIN(
            SELECT
                CODESTRUTURA, OPERACAO, CODROTINA, CODORDPROD, NIVELORDPROD
            FROM HINOERP_BIO.PDORDEMPRODROTINAS) ROTINA
            ON GERAIS.CODESTRUTURA = ROTINA.CODESTRUTURA AND GERAIS.OPERACAO = ROTINA.OPERACAO AND GERAIS.NIVELORDPROD = ROTINA.NIVELORDPROD AND GERAIS.CODORDPROD = ROTINA.CODORDPROD
        LEFT JOIN(
            SELECT 
                *
            FROM (
                SELECT 
                    FUNCIONARIOUSER.CODFUNCIONARIO, NOMES.NOME
                FROM HINOERP_BIO.GEUSUARIOS NOMES
                JOIN (
                    SELECT 
                        CODFUNCIONARIO, CODUSUARIO
                    FROM HINOERP_BIO.GEFUNCIONARIOS) FUNCIONARIOUSER
                ON FUNCIONARIOUSER.CODUSUARIO = NOMES.CODUSUARIO)) INFOCOLABORADOR
                ON INFOCOLABORADOR.CODFUNCIONARIO = GERAIS.CODFUNCIONARIO
        LEFT JOIN (
            SELECT 
                DESCRICAO DESCRICAOMAQ, CODMAQUINA
            FROM HINOERP_BIO.ENMAQUINAS) MAQUINASINFO
            ON MAQUINASINFO.CODMAQUINA = GERAIS.CODMAQUINA

        WHERE CODROTINA IN (${routines})
        ORDER BY CODROTINA, STATUS DESC, GERAIS.CODORDPROD
        `;
    },
    availableUsers: `
    SELECT
        GEFUNCIONARIOS.IDENTIFICACAO,
        GEUSUARIO.NOME
    FROM HINOERP_BIO.GEFUNCIONARIOS GEFUNCIONARIOS
    LEFT JOIN 
        (SELECT 
            CODUSUARIO,
            NOME
        FROM HINOERP_BIO.GEUSUARIOS) GEUSUARIO
        ON GEFUNCIONARIOS.CODUSUARIO = GEUSUARIO.CODUSUARIO
    WHERE STATUS = 1
    ORDER BY NOME
    `,
};
